server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: RentACarUserDB
      username: burcuser
      password: root

jwt:
  secretKey: ${rentCar_secretKey}
  issuer: ${rentCar_issuer}
  audience: ${rentCar_audience}